[package]
name = "flew-core"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
bincode = "1.3.3"
serde_json = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
proc-macro2 = "1.0"
