[package]
name = "flew-core"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.3.0", features = ["v4"] }
